import { GoogleGenerativeAI } from "@google/generative-ai";
import { createClient } from "@/lib/supabase/server";
import { decrypt } from "@/lib/crypto";

export interface AIProviderKeys {
    openai_key_encrypted?: string;
    gemini_key_encrypted?: string;
    active_provider: "openai" | "gemini" | "qwen" | "kimi";
}

export async function getActiveAIProvider(organizationId: string): Promise<AIProviderKeys | null> {
    const supabase = await createClient();
    const { data: apiKeys } = await supabase
        .from("api_keys")
        .select("*")
        .eq("organization_id", organizationId)
        .single();

    return apiKeys;
}

export async function generateEmbedding(text: string, keys: AIProviderKeys): Promise<number[] | null> {
    if (keys.active_provider === "openai" && keys.openai_key_encrypted) {
        const apiKey = decrypt(keys.openai_key_encrypted);
        const response = await fetch("https://api.openai.com/v1/embeddings", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${apiKey}`,
            },
            body: JSON.stringify({
                model: "text-embedding-3-small",
                input: text,
            }),
        });

        const data = await response.json();
        return data.data?.[0]?.embedding || null;
    }

    // Fallback or other providers can be added here
    return null;
}

export async function getAICompletion(prompt: string, keys: AIProviderKeys, systemPrompt?: string): Promise<string | null> {
    const provider = keys.active_provider;

    try {
        if (provider === "openai" && keys.openai_key_encrypted) {
            const apiKey = decrypt(keys.openai_key_encrypted);
            const response = await fetch("https://api.openai.com/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${apiKey}`,
                },
                body: JSON.stringify({
                    model: "gpt-4o-mini",
                    messages: [
                        { role: "system", content: systemPrompt || "You are a helpful CRM assistant." },
                        { role: "user", content: prompt }
                    ],
                }),
            });
            const data = await response.json();
            return data.choices?.[0]?.message?.content || null;
        }

        if (provider === "gemini" && keys.gemini_key_encrypted) {
            const apiKey = decrypt(keys.gemini_key_encrypted);
            const genAI = new GoogleGenerativeAI(apiKey);
            const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
            const result = await model.generateContent((systemPrompt ? systemPrompt + "\n\n" : "") + prompt);
            return result.response.text();
        }
    } catch (error) {
        console.error(`[AI Service] Error with ${provider}:`, error);
    }

    return null;
}

export async function generateContactScore(
    contact: Record<string, unknown>,
    activities: Record<string, unknown>[],
    keys: AIProviderKeys
): Promise<{ score: number; reason: string } | null> {
    const systemPrompt = `You are an expert sales CRM assistant. Your job is to analyze a contact and their activity history, and assign a lead score from 0 to 100.
0-33 = Cold
34-66 = Warm
67-100 = Hot

Evaluate based on:
1. Completeness of profile (company, title, phone).
2. Number of activities (emails, calls, meetings).
3. Recency of activities.
4. Positive signals (email opens, link clicks, form submissions).

You must respond ONLY with a JSON object in this format:
{"score": 85, "reason": "High engagement, opened 3 emails and scheduled a meeting."}`;

    const prompt = `Contact Profile:
${JSON.stringify({
        name: contact.first_name + " " + (contact.last_name || ""),
        company: contact.company,
        title: contact.job_title,
        email: contact.email,
        phone: contact.phone,
        created_at: contact.created_at,
    }, null, 2)}

Recent Activities:
${JSON.stringify(activities.slice(0, 10).map((a: any) => ({
        type: a.type,
        title: a.title,
        date: a.created_at,
        metadata: a.metadata
    })), null, 2)}`;

    try {
        const responseText = await getAICompletion(prompt, keys, systemPrompt);
        if (!responseText) return null;

        // Clean up markdown block if present
        const cleanedText = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
        const parsed = JSON.parse(cleanedText);

        return {
            score: typeof parsed.score === 'number' ? parsed.score : parseInt(parsed.score) || 0,
            reason: parsed.reason || "Score generated by AI"
        };
    } catch (error) {
        console.error("[generateContactScore] Error parsing AI response:", error);
        return null;
    }
}
